<!DOCTYPE html>
<!-- Generated by pkgdown: do not edit by hand --><html lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Introduction to eemR • eemR</title>
<!-- jquery --><script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script><!-- Bootstrap --><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha256-916EbMg70RQy9LHiGkXzG8hSg9EdNy97GazNG/aiY1w=" crossorigin="anonymous">
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha256-U5ZEeKfGNOja007MMD3YBI0A3OSZOQbeG6z2f2Y0hu8=" crossorigin="anonymous"></script><!-- Font Awesome icons --><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" integrity="sha256-eZrrJcwDc/3uDhsdt61sL2oOBY362qM3lon1gyExkL0=" crossorigin="anonymous">
<!-- clipboard.js --><script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/2.0.4/clipboard.min.js" integrity="sha256-FiZwavyI2V6+EXO1U+xzLG3IKldpiTFf3153ea9zikQ=" crossorigin="anonymous"></script><!-- sticky kit --><script src="https://cdnjs.cloudflare.com/ajax/libs/sticky-kit/1.1.3/sticky-kit.min.js" integrity="sha256-c4Rlo1ZozqTPE2RLuvbusY3+SU1pQaJC0TjuhygMipw=" crossorigin="anonymous"></script><!-- pkgdown --><link href="../pkgdown.css" rel="stylesheet">
<script src="../pkgdown.js"></script><meta property="og:title" content="Introduction to eemR">
<meta property="og:description" content="">
<meta name="twitter:card" content="summary">
<!-- mathjax --><script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js" integrity="sha256-nvJJv9wWKEm88qvoQl9ekL2J+k/RWIsaSScxxlsrv8k=" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/config/TeX-AMS-MML_HTMLorMML.js" integrity="sha256-84DKXVJXs0/F8OTMzX4UR909+jtl4G7SPypPavF+GfA=" crossorigin="anonymous"></script><!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]-->
</head>
<body>
    <div class="container template-article">
      <header><div class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <span class="navbar-brand">
        <a class="navbar-link" href="../index.html">eemR</a>
        <span class="version label label-default" data-toggle="tooltip" data-placement="bottom" title="Released version">0.2.9000</span>
      </span>
    </div>

    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
<li>
  <a href="../index.html">
    <span class="fa fa-home fa-lg"></span>
     
  </a>
</li>
<li>
  <a href="../reference/index.html">Reference</a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Articles
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
<li>
      <a href="../articles/custom-import-function.html">Creating custom import functions</a>
    </li>
    <li>
      <a href="../articles/introduction.html">Introduction to eemR</a>
    </li>
  </ul>
</li>
<li>
  <a href="../news/index.html">Changelog</a>
</li>
      </ul>
<ul class="nav navbar-nav navbar-right">
<li>
  <a href="https://github.com/PMassicotte/eemR">
    <span class="fa fa-github fa-lg"></span>
     
  </a>
</li>
      </ul>
</div>
<!--/.nav-collapse -->
  </div>
<!--/.container -->
</div>
<!--/.navbar -->

      
      </header><div class="row">
  <div class="col-md-9 contents">
    <div class="page-header toc-ignore">
      <h1>Introduction to eemR</h1>
                        <h4 class="author">Philippe Massicotte</h4>
            
            <h4 class="date">2019-06-12</h4>
      
      <small class="dont-index">Source: <a href="https://github.com/PMassicotte/eemR/blob/master/vignettes/introduction.Rmd"><code>vignettes/introduction.Rmd</code></a></small>
      <div class="hidden name"><code>introduction.Rmd</code></div>

    </div>

    
    
<div id="introduction" class="section level2">
<h2 class="hasAnchor">
<a href="#introduction" class="anchor"></a>Introduction</h2>
<p>Dissolved organic matter (DOM) plays a central role in the functioning of aquatic ecosystems. For example, characteristics of the DOM pool (quantity and quality) determine underwater light climate <span class="citation">(Kirk 1994)</span>, the composition of aquatic microbial communities <span class="citation">(Foreman and Covert 2003; Kritzberg et al. 2006)</span> and the carbon cycling on local to global scales <span class="citation">(Cole et al. 2007)</span>. Chemically, the DOM pool is complex (&gt; 1500 compounds) and analytical methods used to characterize it are relatively complex, time-consuming and costly <span class="citation">(Benner 2002; Seitzinger et al. 2005; Fellman, Hood, and Spencer 2010)</span>. This situation called for the development of rapid and cost effective characterization techniques. Because optical properties of DOM can be related to its chemical properties, optical techniques such as fluorescence spectroscopy have been developed and rapidly adopted by the community to characterize the DOM pool in aquatic ecosystems <span class="citation">(Coble et al. 1990; Coble 1996; McKnight et al. 2001)</span>.</p>
<p>The seminal paper of <span class="citation">(Stedmon, Markager, and Bro 2003)</span> put at the forefront the use of parallel factor analysis (PARAFAC) to aid the characterization of fluorescent DOM. Briefly, this three-way technique allows the decomposition of complex DOM fluorescence signals contained in the excitation-emission matrix (EEM, Fig. 1) into a set of individual chemical components and provides estimations of their relative contribution to the total fluorescence <span class="citation">(Bro 1997; Fellman, Hood, and Spencer 2010; Stedmon, Markager, and Bro 2003)</span>.</p>
<div class="figure" style="text-align: center">
<img src="introduction_files/figure-html/fig1-1.png" alt="Example of an excitation-emission fluorescence matrix (EEM). The diagonal structure with high fluorescence corresponds to the first order of Rayleigh scattering." width="480"><p class="caption">
Example of an excitation-emission fluorescence matrix (EEM). The diagonal structure with high fluorescence corresponds to the first order of Rayleigh scattering.
</p>
</div>
<p>The PARAFAC model is described as <span class="citation">(Bro 1997; Harshman 1970)</span>:</p>
<div class="equation">
<ol class="example" style="list-style-type: decimal">
<li><span class="math display">\[x_{ijk} = \sum_{f=1}^{F} a_{ij}b_{jf}c_{kf} + e_{ijk}\]</span></li>
</ol>
</div>
<p>where <span class="math inline">\(i = 1, ..., I\)</span>; <span class="math inline">\(j = 1, ..., J\)</span>; <span class="math inline">\(k = 1, ..., K\)</span>, <span class="math inline">\(x_{ijk}\)</span> is the intensity of fluorescence of the the <span class="math inline">\(i^{th}\)</span> sample at the <span class="math inline">\(j^{th}\)</span> emission wavelength at the <span class="math inline">\(k^{th}\)</span> excitation wavelength. <span class="math inline">\(a_{ij}\)</span> is directly proportional to the concentration of the <span class="math inline">\(f^{th}\)</span> component in the sample <span class="math inline">\(i\)</span>. Although PARAFAC gained a lot of attention in environmental sciences, it is also widely used in other research fields such as medical, pharmaceutical, food, social and information sciences <span class="citation">(Murphy et al. 2013)</span>. Until today, more than 1850 published scientific papers relying on PARAFAC have been identified on Web of Science.</p>
<p>Although PARAFAC was made easier using the  MATLAB toolbox <span class="citation">(Murphy et al. 2013)</span>, preprocessing of EEMs prior to the analysis is still not straightforward. EEM preprocessing is an important part of PARAFAC since it aims to correct any systematic bias in the measurements and to remove signal unrelated to DOM fluorescence <span class="citation">(Murphy et al. 2013)</span>. Biased models can be produced if these steps are not conducted carefully (see <span class="citation">Hiriart-Baer, Diep, and Smith (2008)</span> where scattering fluorescence signals have been modeled and wrongly interpreted). Such data processing is cumbersome as it involves many steps <span class="citation">(Stedmon and Bro 2008; Murphy et al. 2013)</span> which are usually executed by hand or within in-house scripting and therefore prone to introduce errors. Another important drawback limiting effective preprocessing of EEMs arise from the wide variety of file formats provided by the different manufacturers of spectrofluorometers that makes data importation difficult to generalize.</p>
<p>Possibly reflecting these difficulties, it was recently pointed out that characterization of DOM using fluorescence spectroscopy is still not routinely included in ecological studies <span class="citation">(Fellman, Hood, and Spencer 2010)</span>. Given the increasing interest for fluorescence spectroscopy in ecology, tools are needed to unify the main preprocessing steps needed for further analyzes such as PARAFAC or metric calculations. The purpose of the   package is to provide a rapid and an elegant interface to perform preprocessing of EEMs as well as to extract common fluorescence-based metrics proposed in the literature to obtain quantitative information about the DOM pool. This paper presents theoretical and mathematical background of the main PARAFAC preprocessing steps and metric calculations with concrete code examples.</p>
</div>
<div id="fluorescence-of-dom-theoretical-and-mathematical-background" class="section level2">
<h2 class="hasAnchor">
<a href="#fluorescence-of-dom-theoretical-and-mathematical-background" class="anchor"></a>Fluorescence of DOM: theoretical and mathematical background</h2>
<p>Let us define <span class="math inline">\(X\)</span>, an EEM of fluorescence intensities measured along a vector of excitation wavelengths (<span class="math inline">\(ex\)</span>) at emission wavelengths (<span class="math inline">\(em\)</span>). Usually, <span class="math inline">\(ex\)</span> and <span class="math inline">\(em\)</span> vary, respectively, between 200-500 nm and 220-600 nm (Fig. 1). <span class="math inline">\(X_{ex, em}\)</span> denotes the fluorescence intensity measured at excitation <span class="math inline">\(ex\)</span> and emission <span class="math inline">\(em\)</span> (ex.: <span class="math inline">\(X_{250, 400}\)</span>).</p>
<p>The following sections present the main correction steps for fluorescence data aiming to correct any systematic bias in the measurements and remove signal unrelated to fluorescence prior to any analysis.</p>
<table class="table">
<colgroup>
<col width="34%">
<col width="65%">
</colgroup>
<thead><tr class="header">
<th>Correction</th>
<th align="center">Description</th>
</tr></thead>
<tbody>
<tr class="odd">
<td>Blank subtraction</td>
<td align="center">Subtract a pure water sample blank from the fluorescence data to help the removal of Raman and Rayleigh scattering peaks.</td>
</tr>
<tr class="even">
<td>Scattering removal</td>
<td align="center">Remove the the so-called scattering bands caused by first and second order of Raman and Rayleigh scattering.</td>
</tr>
<tr class="odd">
<td>Inner-filter effect correction</td>
<td align="center">Correct for reabsorption of light occurring at both the excitation and emission wavelengths during measurement.</td>
</tr>
<tr class="even">
<td>Raman normalization</td>
<td align="center">Remove the dependency of fluorescence intensities from the measuring equipments thus allowing cross-study comparisons.</td>
</tr>
</tbody>
</table>
<div id="scattering-correction" class="section level3">
<h3 class="hasAnchor">
<a href="#scattering-correction" class="anchor"></a>Scattering correction</h3>
<p>Rayleigh and Raman scattering are optical processes by which some of the incident energy can be absorbed and converted into vibrational and rotational energy <span class="citation">(Lakowicz 2006)</span>. The resulting scattered energy produce the so-called scattering bands which are visually easily identifiable (Figs. 1 and 2). Given that both types of scattering are repeated across EEMs, it is important to remove such artifacts prior to analysis <span class="citation">(Bahram et al. 2006; Zepp, Sheldon, and Moran 2004)</span>.</p>
<div class="figure" style="text-align: center">
<img src="introduction_files/figure-html/fig2-1.png" alt="Emission fluorescence emitted at excitation $ex = 350$. First order of Rayleigh and Raman scattering regions are identified in blue and red." width="480"><p class="caption">
Emission fluorescence emitted at excitation <span class="math inline">\(ex = 350\)</span>. First order of Rayleigh and Raman scattering regions are identified in blue and red.
</p>
</div>
<p>First order of Rayleigh scattering is defined as the region where emission is equal to excitation (<span class="math inline">\(em = ex\)</span>) causing a diagonal band in the EEM (Fig. 1) whereas the second order of Rayleigh scattering occurs at two times the emission wavelength of the primary peak (<span class="math inline">\(em = 2ex\)</span>). For water, Raman scattering occurs at a wavenumber 3 600 <span class="math inline">\(cm^{-1}\)</span> (or <span class="math inline">\(3.6 \times 10^{10} nm^{-1}\)</span>) lower than the incident excitation wavenumber <span class="citation">(Lakowicz 2006)</span>. Mathematically, first order Raman scattering is defined as follow:</p>
<div class="equation">
<ol start="2" class="example" style="list-style-type: decimal">
<li><span class="math display">\[\text{Raman}_{\text{1st}} = -\frac{ex}{0.00036 ex - 1}\]</span></li>
</ol>
</div>
<p>where <span class="math inline">\(ex\)</span> is the incident excitation wavelength (nm). Second order Raman scattering is then simply defined as:</p>
<div class="equation">
<ol start="3" class="example" style="list-style-type: decimal">
<li><span class="math display">\[\text{Raman}_{\text{2nd}} = -\frac{2ex}{0.00036 ex - 1}\]</span></li>
</ol>
</div>
<p>Different interpolation techniques have been proposed to eliminate scattering <span class="citation">(Zepp, Sheldon, and Moran 2004; Bahram et al. 2006)</span>. However, it is a common practice to simply remove the scattering-bands by inserting missing values (Fig. 3) at the corresponding positions <span class="citation">(Murphy et al. 2013; Stedmon and Bro 2008)</span>.</p>
</div>
<div id="inner-filter-effect-correction" class="section level3">
<h3 class="hasAnchor">
<a href="#inner-filter-effect-correction" class="anchor"></a>Inner-filter effect correction</h3>
<p>The inner-filter effect (IFE) is an optical phenomenon of reabsorption of emitted light and occurs particularly in highly concentrated samples (Fig. 4). IFE is known to cause underestimation of fluorescence intensities especially at shorter wavelengths and even to alter the shape and the positioning of fluorescence spectra by shifting peak positions toward lower wavelengths (Fig. 4) with increasing concentration <span class="citation">(Mobed et al. 1996; Kothawala et al. 2013)</span>. However, it was shown that the loss of fluorescence due to IFE could be estimated from absorbance spectra measured on the same sample using Equation (4) <span class="citation">(Ohno 2002; Parker and Barnes 1957)</span>:</p>
<div class="equation">
<ol start="4" class="example" style="list-style-type: decimal">
<li><span class="math display">\[X_0 = \frac{X}{10^{-b(A_{ex} + A_{em})}}\]</span></li>
</ol>
</div>
<p>where <span class="math inline">\(X_0\)</span> is the fluorescence in the absence of IFE, <span class="math inline">\(X\)</span> is the measured fluorescence intensity, <span class="math inline">\(b\)</span> is half the cuvette pathlength (usually 0.5 cm) for excitation and emission absorbance, <span class="math inline">\(A_{ex}\)</span> is the absorbance at the excitation wavelength <span class="math inline">\(ex\)</span> and <span class="math inline">\(A_{em}\)</span> the absorbance at the emission wavelength <span class="math inline">\(em\)</span> (Fig. 4B).</p>
<div class="figure" style="text-align: center">
<img src="introduction_files/figure-html/fig3-1.png" alt="Surface plot of an EEM with first order of Raman and Rayleigh scattering removed. Missing values (`NA`) have been placed in both diagonals using a bandwidth of 10 nm." width="672"><p class="caption">
Surface plot of an EEM with first order of Raman and Rayleigh scattering removed. Missing values (<code>NA</code>) have been placed in both diagonals using a bandwidth of 10 nm.
</p>
</div>
<p>It was recently shown that IFE corrected algebraically was not appropriate when total absorbance, defined as <span class="math inline">\(A_{\text{total}} = A_{\text{ex}} + A_{\text{em}}\)</span> (see Equation (4)), is greater than 1.5 <span class="citation">(Kothawala et al. 2013)</span>. Under this circumstance, a two-fold dilution of the sample has been recommended. If this happen, a warning message will be displayed by the package during the correction process.</p>
</div>
<div id="raman-calibration" class="section level3">
<h3 class="hasAnchor">
<a href="#raman-calibration" class="anchor"></a>Raman calibration</h3>
<p>The same DOM sample measured on different spectrofluorometers (or even the same but with different settings) can give important differences in fluorescence intensities <span class="citation">(Lawaetz and Stedmon 2009; Coble, Schultz, and Mopper 1993)</span>. The purpose of the Raman calibration is to remove the dependency of fluorescence intensities on the measuring equipment, thus allowing cross-study comparisons. Given that the Raman peak position of a water sample is located at a fixed position, <span class="citation">(Lawaetz and Stedmon 2009)</span> proposed to use the Raman integral of a blank-water sample measured the same day as the EEM to perform calibration. Moreover, the area of the Raman peak (<span class="math inline">\(A_{\text{rp}}\)</span>, Fig. 5) is defined as the area of the emission profile between 371 and 428 nm at a fixed excitation of 350 nm <span class="citation">(Lawaetz and Stedmon 2009)</span>.</p>
<div class="figure" style="text-align: center">
<img src="introduction_files/figure-html/fig4-1.png" alt="IFE correction process. Panel (A) shows an uncorrected EEM (the color bar is the florescence intensity in A.U.). Panel (B) is the corresponding absorbance spectra measured on the same sample. Panel (C) shows the IFE correction factors corresponding to the values of the denominator in Equation (@ife) with values close to 1 indicating less pronounced correction. Panel (D) shows the corrected sample (the color bar is the fluorescence intensity in A.U.)." width="672"><p class="caption">
IFE correction process. Panel (A) shows an uncorrected EEM (the color bar is the florescence intensity in A.U.). Panel (B) is the corresponding absorbance spectra measured on the same sample. Panel (C) shows the IFE correction factors corresponding to the values of the denominator in Equation (4) with values close to 1 indicating less pronounced correction. Panel (D) shows the corrected sample (the color bar is the fluorescence intensity in A.U.).
</p>
</div>
<p>Mathematically, the value of <span class="math inline">\(A_{\text{rp}}\)</span> is calculated using the following integral (Equation(5)):</p>
<div class="equation">
<ol start="5" class="example" style="list-style-type: decimal">
<li><span class="math display">\[A_{\text{rp}} = \int\limits_{\lambda_{\text{em}371}}^{\lambda_{\text{em}428}} W_{350, \lambda} d\lambda\]</span></li>
</ol>
</div>
<p>where <span class="math inline">\(W_{350, \lambda}\)</span> is the fluorescence intensity of a pure water sample (preferably deionized and ultraviolet exposed, <span class="citation">Lawaetz and Stedmon (2009)</span>) at excitation <span class="math inline">\(ex = 350\)</span> nm and at emission <span class="math inline">\(em = \lambda\)</span> nm. Each values of the EEM <span class="math inline">\(X\)</span> are then normalized using the scalar value of <span class="math inline">\(A_{\text{rp}}\)</span> accordingly to Equation (6):</p>
<div class="equation">
<ol start="6" class="example" style="list-style-type: decimal">
<li><span class="math display">\[X_0 = \frac{X}{A_{\text{rp}}}\]</span></li>
</ol>
</div>
<p>where <span class="math inline">\(X_0\)</span> is the normalized EEM with fluorescence intensities now expressed as Raman Units (R.U.), <span class="math inline">\(X\)</span> are the unnormalized measured fluorescence intensities and <span class="math inline">\(A_{\text{rp}}\)</span> is the Raman peak area.</p>
</div>
<div id="metrics" class="section level3">
<h3 class="hasAnchor">
<a href="#metrics" class="anchor"></a>Metrics</h3>
<p>A wide range of different metrics obtained from EEMs have been proposed to characterize the DOM pool in aquatic ecosystems. These metrics extract quantitative information in specific regions (wavelengths) in EEMs. The following sections present an overview of the principal metrics supported by the package.</p>
<div id="cobles-peaks" class="section level4">
<h4 class="hasAnchor">
<a href="#cobles-peaks" class="anchor"></a>Coble’s peaks</h4>
<p>The following table presents the five major fluorescent components identified by <span class="citation">(Coble 1996)</span> in marine EEMs. Peaks <strong>B</strong> and <strong>T</strong> represent protein-like compounds (tyrosine and tryptophane), peaks <strong>A</strong> and <strong>C</strong> are indicators of humic-like components whereas peak <strong>M</strong> was associated to marine humic-like fluorescence.</p>
<table class="table">
<thead><tr class="header">
<th>Peak</th>
<th>Ex (nm)</th>
<th>Em (nm)</th>
</tr></thead>
<tbody>
<tr class="odd">
<td>B</td>
<td>275</td>
<td>310</td>
</tr>
<tr class="even">
<td>T</td>
<td>275</td>
<td>340</td>
</tr>
<tr class="odd">
<td>A</td>
<td>260</td>
<td>380-460</td>
</tr>
<tr class="even">
<td>M</td>
<td>312</td>
<td>380-420</td>
</tr>
<tr class="odd">
<td>C</td>
<td>350</td>
<td>420-480</td>
</tr>
</tbody>
</table>
</div>
<div id="fluorescence-humification-and-biological-indices" class="section level4">
<h4 class="hasAnchor">
<a href="#fluorescence-humification-and-biological-indices" class="anchor"></a>Fluorescence, humification and biological indices</h4>
<p>Three main indices have been proposed to trace the diagnostic state of the DOM pool in aquatic ecosystems. The fluorescence index (FI) was shown to be a good indicator of the general source and aromaticity of DOM in lakes, streams and rivers <span class="citation">(McKnight et al. 2001)</span>. This index is calculated as the ratio of fluorescence at emission 450 nm and 500 nm, at fixed excitation of 370 nm (Equation (7)).</p>
<div class="equation">
<ol start="7" class="example" style="list-style-type: decimal">
<li><span class="math display">\[\text{FI} = \frac{X_{370, 450}}{X_{370, 500}}\]</span></li>
</ol>
</div>
<p>The humification index (HIX) is a measure of the complexity and the aromatic nature of DOM <span class="citation">(Ohno 2002)</span>. HIX calculated as the ratio of the sum of the fluorescence between 435 and 480 nm and between 300 and 345 nm at a fixed excitation of 254 nm (Equation (8)).</p>
<div class="equation">
<ol start="8" class="example" style="list-style-type: decimal">
<li><span class="math display">\[\text{HIX} = \frac{\sum\limits_{em = 435}^{480} X_{254, em}}{\sum\limits_{em = 300}^{345} X_{254, em}}\]</span></li>
</ol>
</div>
<p>The biological index (BIX) is a measure to characterize biological production of DOM <span class="citation">(Huguet et al. 2009)</span>. BIX is calculated at excitation 310 nm, by dividing the fluorescence intensity emitted at emission 380 nm and at 430 nm (Equation (9)).</p>
<div class="equation">
<ol start="9" class="example" style="list-style-type: decimal">
<li><span class="math display">\[\text{BIX} = \frac{X_{310, 380}}{X_{310, 430}}\]</span></li>
</ol>
</div>
</div>
</div>
</div>
<div id="r-code-and-study-case" class="section level2">
<h2 class="hasAnchor">
<a href="#r-code-and-study-case" class="anchor"></a>R code and study case</h2>
<p>Main preprocessing steps using the <strong>eemR</strong> package are illustrated using a subset of three EEMs from <span class="citation">(Massicotte and Frenette 2011)</span>. Briefly, these EEMs (see Fig. 1 for an example) have been sampled in the St. Lawrence River, one of the largest rivers in North America. Fluorescence matrices of DOM were measured on a Cary Eclipse spectrofluorometer (Varian, Mississauga, Ontario, Canada) over excitation wavelengths between 220 and 450 nm (5-nm increment) and emission wavelengths between 230 and 600 nm (2-nm increment). All functions from the package start with the prefix <code>'eem_'</code>.</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb1-1" data-line-number="1"><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/library">library</a></span>(eemR)</a>
<a class="sourceLine" id="cb1-2" data-line-number="2"><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/ls">ls</a></span>(<span class="st">"package:eemR"</span>)</a></code></pre></div>
<pre><code>##  [1] "absorbance"              "eem_bind"               
##  [3] "eem_biological_index"    "eem_coble_peaks"        
##  [5] "eem_cut"                 "eem_export_matlab"      
##  [7] "eem_extract"             "eem_fluorescence_index" 
##  [9] "eem_humification_index"  "eem_inner_filter_effect"
## [11] "eem_names"               "eem_names&lt;-"            
## [13] "eem_peaks"               "eem_raman_normalisation"
## [15] "eem_read"                "eem_remove_blank"       
## [17] "eem_remove_scattering"   "eem_set_wavelengths"</code></pre>
<div id="data-importation-and-plotting" class="section level3">
<h3 class="hasAnchor">
<a href="#data-importation-and-plotting" class="anchor"></a>Data importation and plotting</h3>
<p>Importation of EEMs into  is done using the <code><a href="../reference/eem_read.html">eem_read()</a></code> function. Given that fluorescence files are dependent on the spectrofluorometer used,  will determine automatically from which manufacturer the files are from and load them accordingly.</p>
<div class="sourceCode" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb3-1" data-line-number="1">file &lt;-<span class="st"> </span><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/system.file">system.file</a></span>(<span class="st">"extdata/cary/scans_day_1"</span>, <span class="dt">package =</span> <span class="st">"eemR"</span>)</a>
<a class="sourceLine" id="cb3-2" data-line-number="2">eems &lt;-<span class="st"> </span><span class="kw"><a href="../reference/eem_read.html">eem_read</a></span>(file, <span class="dt">import_function =</span> <span class="st">"cary"</span>)</a></code></pre></div>
<p>The generic <code><a href="https://www.rdocumentation.org/packages/base/topics/summary">summary()</a></code> function displays useful information such as: (1) the wavelength ranges used in both emission and excitation modes, (2) the manufacturer from which the file was read and (3) the state of the EEM which indicate which corrections have been applied.</p>
<div class="sourceCode" id="cb4"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb4-1" data-line-number="1"><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/summary">summary</a></span>(eems)</a></code></pre></div>
<pre><code>##    sample ex_min ex_max em_min em_max is_blank_corrected
## 1    nano    220    450    230    600              FALSE
## 2 sample1    220    450    230    600              FALSE
## 3 sample2    220    450    230    600              FALSE
## 4 sample3    220    450    230    600              FALSE
##   is_scatter_corrected is_ife_corrected is_raman_normalized
## 1                FALSE            FALSE               FALSE
## 2                FALSE            FALSE               FALSE
## 3                FALSE            FALSE               FALSE
## 4                FALSE            FALSE               FALSE</code></pre>
<p>A surface plot of EEMs is made using the <code><a href="https://www.rdocumentation.org/packages/graphics/topics/plot">plot(x, which = 1)</a></code> function where <code>which</code> is the index of the EEM to be plotted (see Fig. 3).</p>
<div class="sourceCode" id="cb6"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb6-1" data-line-number="1"><span class="kw"><a href="https://www.rdocumentation.org/packages/graphics/topics/plot">plot</a></span>(eems, <span class="dt">which =</span> <span class="dv">3</span>)</a></code></pre></div>
<p>Interactive plots using a simple shiny app can be lunched to interactively browse EEMs.</p>
<div class="sourceCode" id="cb7"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb7-1" data-line-number="1"><span class="kw"><a href="https://www.rdocumentation.org/packages/graphics/topics/plot">plot</a></span>(eems, <span class="dt">interactive =</span> <span class="ot">TRUE</span>)</a></code></pre></div>
</div>
<div id="blank-subtraction" class="section level3">
<h3 class="hasAnchor">
<a href="#blank-subtraction" class="anchor"></a>Blank subtraction</h3>
<p>Subtraction of a water blank from the measured samples may help to reduce scattering <span class="citation">(Murphy et al. 2013; Stedmon and Bro 2008)</span>. In , this is done using the <code><a href="../reference/eem_remove_blank.html">eem_remove_blank(eem, blank)</a></code> function where <code>eem</code> is a list of EEMs and <code>blank</code> is a water blank.</p>
<div class="sourceCode" id="cb8"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb8-1" data-line-number="1">file &lt;-<span class="st"> </span><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/system.file">system.file</a></span>(<span class="st">"extdata/cary/scans_day_1"</span>, <span class="st">"nano.csv"</span>, <span class="dt">package =</span> <span class="st">"eemR"</span>)</a>
<a class="sourceLine" id="cb8-2" data-line-number="2">blank &lt;-<span class="st"> </span><span class="kw"><a href="../reference/eem_read.html">eem_read</a></span>(file, <span class="dt">import_function =</span> <span class="st">"cary"</span>)</a>
<a class="sourceLine" id="cb8-3" data-line-number="3"></a>
<a class="sourceLine" id="cb8-4" data-line-number="4">eems &lt;-<span class="st"> </span><span class="kw"><a href="../reference/eem_remove_blank.html">eem_remove_blank</a></span>(eems, blank)</a></code></pre></div>
</div>
<div id="raman-and-rayleigh-scattering-removal" class="section level3">
<h3 class="hasAnchor">
<a href="#raman-and-rayleigh-scattering-removal" class="anchor"></a>Raman and Rayleigh scattering removal</h3>
<p>Scattering removal (Equation (2) and Equation (3)) is performed using the <code><a href="../reference/eem_remove_scattering.html">eem_remove_scattering(eem, type, order, width)</a></code> function where <code>eem</code> is a list of EEMs, <code>type</code> is the scattering type (<code>raman</code> or <code>rayleigh</code>), <code>order</code> is the order of the scattering (1 or 2) and <code>width</code> the width in nanometers of the slit windows to be removed. In the following example, only first order and Raman and Rayleigh scattering are removed using a bandwidth of 10 nm (Fig. 3).</p>
<div class="sourceCode" id="cb9"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb9-1" data-line-number="1">eems &lt;-<span class="st"> </span><span class="kw"><a href="../reference/eem_remove_scattering.html">eem_remove_scattering</a></span>(eems, <span class="st">"rayleigh"</span>, <span class="dv">1</span>, <span class="dv">10</span>) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb9-2" data-line-number="2"><span class="st">  </span><span class="kw"><a href="../reference/eem_remove_scattering.html">eem_remove_scattering</a></span>(<span class="st">"raman"</span>, <span class="dv">1</span>, <span class="dv">10</span>)</a>
<a class="sourceLine" id="cb9-3" data-line-number="3"></a>
<a class="sourceLine" id="cb9-4" data-line-number="4"><span class="kw"><a href="https://www.rdocumentation.org/packages/graphics/topics/plot">plot</a></span>(eems, <span class="dt">which =</span> <span class="dv">3</span>)</a></code></pre></div>
<div class="figure" style="text-align: center">
<img src="introduction_files/figure-html/fig5-1.png" alt="Fluorescence profile of a pure water sample at excitation 350 nm between 300 and 450 nm emission. The area of the Raman peak is identified by the shaded polygon and is calculated using Equation (@arp)." width="480"><p class="caption">
Fluorescence profile of a pure water sample at excitation 350 nm between 300 and 450 nm emission. The area of the Raman peak is identified by the shaded polygon and is calculated using Equation (5).
</p>
</div>
</div>
<div id="inner-filter-effect-correction-1" class="section level3">
<h3 class="hasAnchor">
<a href="#inner-filter-effect-correction-1" class="anchor"></a>Inner-filter effect correction</h3>
<p>IFE correction requires the use of absorbance data (Equation (4)). For each EEM, an absorbance spectra must be supplied. The easiest way to provide absorbance is to use a data frame with column names matching EEMs names. In the following data frame, the first column represents the wavelengths at which absorbance have been measured whereas the remaining columns are absorbance spectra for <code>sample1</code>, <code>sample2</code> and <code>sample3</code>.</p>
<div class="sourceCode" id="cb10"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb10-1" data-line-number="1"><span class="kw"><a href="https://www.rdocumentation.org/packages/utils/topics/data">data</a></span>(<span class="st">"absorbance"</span>)</a>
<a class="sourceLine" id="cb10-2" data-line-number="2"><span class="kw"><a href="https://www.rdocumentation.org/packages/utils/topics/head">head</a></span>(absorbance)</a></code></pre></div>
<pre><code>##   wavelength sample1 sample2 sample3
## 1        190 0.89674 1.02927 1.19405
## 2        191 0.84894 0.96381 1.13721
## 3        192 0.77267 0.85339 1.04520
## 4        193 0.70967 0.75627 0.96782
## 5        194 0.65459 0.67145 0.90092
## 6        195 0.61371 0.60745 0.85054</code></pre>
<p>Note that EEM names can be obtained using the <code>eem_sample_names()</code> function.</p>
<div class="sourceCode" id="cb12"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb12-1" data-line-number="1"><span class="kw"><a href="../reference/eem_names.html">eem_names</a></span>(eems)</a></code></pre></div>
<pre><code>## [1] "nano"    "sample1" "sample2" "sample3"</code></pre>
<p>IFE correction is performed using the <code><a href="../reference/eem_inner_filter_effect.html">eem_inner_filter_effect(eem, absorbance, pathlength)</a></code> function where <code>eem</code> is a list of EEMs, <code>absorbance</code> is a data frame containing absorbance spectra and <code>pathlength</code> is the absorbance cuvette pathlength expressed in <span class="math inline">\(cm\)</span> (Fig. 4B). For each EEM contained in <code>eem</code>, the ranges spanned by the IFE correction factors and total absorbance <span class="math inline">\(A_{\text{total}}\)</span> (Equation (4)) are displayed to the user. This can serve as diagnostic tool to determine if the mathematical correction was the appropriate method to use to handle IFE.</p>
<div class="sourceCode" id="cb14"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb14-1" data-line-number="1">eems &lt;-<span class="st"> </span><span class="kw"><a href="../reference/eem_inner_filter_effect.html">eem_inner_filter_effect</a></span>(<span class="dt">eem =</span> eems,</a>
<a class="sourceLine" id="cb14-2" data-line-number="2">                                <span class="dt">absorbance =</span> absorbance,</a>
<a class="sourceLine" id="cb14-3" data-line-number="3">                                <span class="dt">pathlength =</span> <span class="dv">1</span>)</a></code></pre></div>
<pre><code>## Warning: Absorbance spectrum for nano was not found. Returning uncorrected
## EEM.</code></pre>
<pre><code>## sample1 
## Range of IFE correction factors: 1.0112 1.5546 
## Range of total absorbance (Atotal) : 0.0096 0.3832 
## 
## sample2 
## Range of IFE correction factors: 1.0061 1.3124 
## Range of total absorbance (Atotal) : 0.0053 0.2362 
## 
## sample3 
## Range of IFE correction factors: 1.016 2.3713 
## Range of total absorbance (Atotal) : 0.0138 0.75</code></pre>
<div class="sourceCode" id="cb17"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb17-1" data-line-number="1"><span class="kw"><a href="https://www.rdocumentation.org/packages/graphics/topics/plot">plot</a></span>(eems, <span class="dt">which =</span> <span class="dv">3</span>)</a></code></pre></div>
<p>Fig. 4 presents intermediate results obtained for the correction of <code>sample3</code>. Note the nonlinearity of the correction with higher effect at lower wavelengths (bottom-left corner in panel C). The corrected EEM is presented in Fig. 4D which is the result of the operation of dividing matrix in 4A by 4C.</p>
</div>
<div id="raman-normalization" class="section level3">
<h3 class="hasAnchor">
<a href="#raman-normalization" class="anchor"></a>Raman normalization</h3>
<p>The last step of the correction process consist to calibrate fluorescence intensities using the Raman scatter peak of water <span class="citation">(Lawaetz and Stedmon 2009)</span>. This is performed using the <code><a href="../reference/eem_raman_normalisation.html">eem_raman_normalisation(eem, blank)</a></code> function where <code>eem</code> is a list of EEMs and <code>blank</code> is a water blank measured the same day. Here, the same water-blank is used for the three EEMs. Note that the value of the Raman area (<span class="math inline">\(A_{\text{rp}}\)</span>, Equation(5)) is printed.</p>
<div class="sourceCode" id="cb18"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb18-1" data-line-number="1">eems &lt;-<span class="st"> </span><span class="kw"><a href="../reference/eem_raman_normalisation.html">eem_raman_normalisation</a></span>(eems, blank)</a></code></pre></div>
<pre><code>## Raman area: 9.540904 
## Raman area: 9.540904 
## Raman area: 9.540904</code></pre>
<div class="sourceCode" id="cb20"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb20-1" data-line-number="1"><span class="kw"><a href="https://www.rdocumentation.org/packages/graphics/topics/plot">plot</a></span>(eems, <span class="dt">which =</span> <span class="dv">3</span>)</a></code></pre></div>
<p>At this stage, all corrections have been performed and EEMs are ready to be exported into MATLAB for PARAFAC analysis. The state of the EEMs can be verified using the <code><a href="https://www.rdocumentation.org/packages/base/topics/summary">summary()</a></code> function.</p>
<div class="sourceCode" id="cb21"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb21-1" data-line-number="1"><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/summary">summary</a></span>(eems)</a></code></pre></div>
<pre><code>##    sample ex_min ex_max em_min em_max is_blank_corrected
## 1    nano    220    450    230    600              FALSE
## 2 sample1    220    450    230    600               TRUE
## 3 sample2    220    450    230    600               TRUE
## 4 sample3    220    450    230    600               TRUE
##   is_scatter_corrected is_ife_corrected is_raman_normalized
## 1                 TRUE            FALSE               FALSE
## 2                 TRUE             TRUE                TRUE
## 3                 TRUE             TRUE                TRUE
## 4                 TRUE             TRUE                TRUE</code></pre>
</div>
<div id="exporting-to-matlab" class="section level3">
<h3 class="hasAnchor">
<a href="#exporting-to-matlab" class="anchor"></a>Exporting to MATLAB</h3>
<p>The <strong>drEEM</strong> MATLAB toolbox <span class="citation">(Murphy et al. 2013)</span> used to perform PARAFAC analysis requires data in a specific format (structure). The <code><a href="../reference/eem_export_matlab.html">eem_export_matlab(file, ...)</a></code> function can be used to export corrected EEMs into a PARAFAC ready format. The first <code>file</code> argument is the mat file where to export the structure and the second argument <code>...</code> is one or more <code>eem</code> object.</p>
<div class="sourceCode" id="cb23"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb23-1" data-line-number="1"><span class="kw"><a href="../reference/eem_export_matlab.html">eem_export_matlab</a></span>(<span class="st">"myfile.mat"</span>, eems)</a></code></pre></div>
<p>Once exported, one can simply import the generated mat file in MATLAB using <code><a href="https://www.rdocumentation.org/packages/base/topics/load">load('myfile.mat');</a></code>.</p>
</div>
<div id="metric-extraction" class="section level3">
<h3 class="hasAnchor">
<a href="#metric-extraction" class="anchor"></a>Metric extraction</h3>
<p>Coble’s peaks can be extracted using the <code><a href="../reference/eem_coble_peaks.html">eem_coble_peaks(eem)</a></code> function. Note that for peaks <strong>A, M, C</strong>, the maximum fluorescence intensity in the range of emission region is returned.</p>
<div class="sourceCode" id="cb24"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb24-1" data-line-number="1">file &lt;-<span class="st"> </span><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/system.file">system.file</a></span>(<span class="st">"extdata/cary/scans_day_1"</span>, <span class="dt">package =</span> <span class="st">"eemR"</span>)</a>
<a class="sourceLine" id="cb24-2" data-line-number="2">eems &lt;-<span class="st"> </span><span class="kw"><a href="../reference/eem_read.html">eem_read</a></span>(file, <span class="dt">import_function =</span> <span class="st">"cary"</span>)</a>
<a class="sourceLine" id="cb24-3" data-line-number="3"></a>
<a class="sourceLine" id="cb24-4" data-line-number="4"><span class="kw"><a href="../reference/eem_coble_peaks.html">eem_coble_peaks</a></span>(eems, <span class="dt">verbose =</span> <span class="ot">FALSE</span>)</a></code></pre></div>
<pre><code>##    sample         b         t        a          m         c
## 1    nano 0.8745673 0.1401188 0.140175 0.09653326 0.1255788
## 2 sample1 1.5452981 1.0603312 3.731836 2.42409567 1.8149415
## 3 sample2 1.2629968 0.6647042 1.583489 1.02359302 0.7709074
## 4 sample3 1.4740862 1.3162812 8.416034 6.06335506 6.3179129</code></pre>
<p>Fluorescence (FI), humification (HIX) and biological (BIX) indices can be extracted as follow.</p>
<div class="sourceCode" id="cb26"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb26-1" data-line-number="1"><span class="kw"><a href="../reference/eem_fluorescence_index.html">eem_fluorescence_index</a></span>(eems, <span class="dt">verbose =</span> <span class="ot">FALSE</span>)</a></code></pre></div>
<pre><code>##    sample         fi
## 1    nano -0.5932057
## 2 sample1  1.2647823
## 3 sample2  1.4553330
## 4 sample3  1.3294132</code></pre>
<div class="sourceCode" id="cb28"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb28-1" data-line-number="1"><span class="kw"><a href="../reference/eem_humification_index.html">eem_humification_index</a></span>(eems, <span class="dt">verbose =</span> <span class="ot">FALSE</span>)</a></code></pre></div>
<pre><code>##    sample        hix
## 1    nano  0.5568136
## 2 sample1  6.3795618
## 3 sample2  4.2548483
## 4 sample3 13.0246234</code></pre>
<div class="sourceCode" id="cb30"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb30-1" data-line-number="1"><span class="kw"><a href="../reference/eem_biological_index.html">eem_biological_index</a></span>(eems, <span class="dt">verbose =</span> <span class="ot">FALSE</span>)</a></code></pre></div>
<pre><code>##    sample       bix
## 1    nano 2.6812045
## 2 sample1 0.7062640
## 3 sample2 0.8535423
## 4 sample3 0.4867927</code></pre>
<p>It should be noted that different excitation and emission wavelengths are often used to measure EEMs. Hence, it is possible to have mismatch between measured wavelengths and wavelengths used to calculate specific metrics. In these circumstances, EEMs are interpolated using the the  package <span class="citation">(Borchers 2015)</span>. A message warning the user will be displayed if data interpolation is performed. This behavior can be controlled using the <code>verbose = TRUE/FALSE</code> parameter.</p>
</div>
</div>
<div id="using-r-pipeline" class="section level2">
<h2 class="hasAnchor">
<a href="#using-r-pipeline" class="anchor"></a>Using R pipeline</h2>
<p>Note that it is also possible to use the <a href="https://CRAN.R-project.org/package=magrittr">magrittr</a> pipe line with most functions from <code>eemR</code>.</p>
<div class="sourceCode" id="cb32"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb32-1" data-line-number="1"><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/library">library</a></span>(magrittr)</a>
<a class="sourceLine" id="cb32-2" data-line-number="2"></a>
<a class="sourceLine" id="cb32-3" data-line-number="3">file &lt;-<span class="st"> </span><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/system.file">system.file</a></span>(<span class="st">"extdata/cary/scans_day_1/"</span>, <span class="dt">package =</span> <span class="st">"eemR"</span>)</a>
<a class="sourceLine" id="cb32-4" data-line-number="4">file <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb32-5" data-line-number="5"><span class="st">  </span><span class="kw"><a href="../reference/eem_read.html">eem_read</a></span>(<span class="dt">recursive =</span> <span class="ot">TRUE</span>, <span class="dt">import_function =</span> <span class="st">"cary"</span>) <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb32-6" data-line-number="6"><span class="st">  </span><span class="kw"><a href="../reference/eem_raman_normalisation.html">eem_raman_normalisation</a></span>() <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb32-7" data-line-number="7"><span class="st">  </span><span class="kw"><a href="../reference/eem_remove_scattering.html">eem_remove_scattering</a></span>(<span class="dt">type =</span> <span class="st">"raman"</span>, <span class="dt">order =</span> <span class="dv">1</span>, <span class="dt">width =</span> <span class="dv">10</span>) <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb32-8" data-line-number="8"><span class="st">  </span><span class="kw"><a href="../reference/eem_remove_scattering.html">eem_remove_scattering</a></span>(<span class="dt">type =</span> <span class="st">"rayleigh"</span>, <span class="dt">order =</span> <span class="dv">1</span>, <span class="dt">width =</span> <span class="dv">10</span>) <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb32-9" data-line-number="9"><span class="st">  </span><span class="kw"><a href="https://www.rdocumentation.org/packages/graphics/topics/plot">plot</a></span>(<span class="dv">2</span>)</a></code></pre></div>
</div>
<div id="conclusion" class="section level2">
<h2 class="hasAnchor">
<a href="#conclusion" class="anchor"></a>Conclusion</h2>
<p> provides a flexible interface for manipulating and preprocessing fluorescence matrices based on theoretical and mathematical foundations of fluorescence spectroscopy <span class="citation">(Lakowicz 2006)</span>. Furthermore, this  package removes the drawbacks associated with EEM manipulation (dependent on spectrofluorometer manufacturer) and unifies the most important steps involved in EEM preparation in order to correct and remove systematic bias in fluorescence measurements. This will likely contribute to promote the use of fluorescence spectroscopy in various fields.</p>
</div>
<div id="references" class="section level2 unnumbered">
<h2 class="hasAnchor">
<a href="#references" class="anchor"></a>References</h2>
<div id="refs" class="references">
<div id="ref-Bahram2006">
<p>Bahram, Morteza, Rasmus Bro, Colin Stedmon, and Abbas Afkhami. 2006. “Handling of Rayleigh and Raman scatter for PARAFAC modeling of fluorescence data using interpolation.” <em>Journal of Chemometrics</em> 20 (3-4): 99–105. <a href="https://doi.org/10.1002/cem.978" class="uri">https://doi.org/10.1002/cem.978</a>.</p>
</div>
<div id="ref-Benner2002">
<p>Benner, R. 2002. “Chemical composition and reactivity.” In <em>Biogeochemistry of Marine Dissolved Organic Matter</em>, edited by Dennis A Hansell and Craig A Carlson, 59–90. San Diego, CA: Academic Press.</p>
</div>
<div id="ref-Borchers2015">
<p>Borchers, Hans Werner. 2015. <em>pracma: Practical Numerical Math Functions</em>. <a href="https://cran.r-project.org/package=pracma" class="uri">https://cran.r-project.org/package=pracma</a>.</p>
</div>
<div id="ref-Bro1997">
<p>Bro, Rasmus. 1997. “PARAFAC. Tutorial and applications.” <em>Chemometrics and Intelligent Laboratory Systems</em> 38 (2): 149–71. <a href="https://doi.org/10.1016/S0169-7439(97)00032-4" class="uri">https://doi.org/10.1016/S0169-7439(97)00032-4</a>.</p>
</div>
<div id="ref-Coble1996">
<p>Coble, Paula G. 1996. “Characterization of marine and terrestrial DOM in seawater using excitation-emission matrix spectroscopy.” <em>Marine Chemistry</em> 51 (4): 325–46. <a href="https://doi.org/10.1016/0304-4203(95)00062-3" class="uri">https://doi.org/10.1016/0304-4203(95)00062-3</a>.</p>
</div>
<div id="ref-Coble1990">
<p>Coble, Paula G, Sarah A Green, Neil V Blough, and Robert B Gagosian. 1990. “Characterization of dissolved organic matter in the Black Sea by fluorescence spectroscopy.” <em>Nature</em> 348 (6300). Coble, Pg Univ Washington,Sch Oceanog,Seattle,Wa 98195, USA Univ Washington,Sch Oceanog,Seattle,Wa 98195, USA Woods Hole Oceanog Inst,Woods Hole,Ma 02543: 432–35. <a href="https://doi.org/10.1038/348432a0" class="uri">https://doi.org/10.1038/348432a0</a>.</p>
</div>
<div id="ref-Coble1993">
<p>Coble, Paula G., Christopher a. Schultz, and Kenneth Mopper. 1993. “Fluorescence contouring analysis of DOC intercalibration experiment samples: a comparison of techniques.” <em>Marine Chemistry</em> 41 (1-3): 173–78. <a href="https://doi.org/10.1016/0304-4203(93)90116-6" class="uri">https://doi.org/10.1016/0304-4203(93)90116-6</a>.</p>
</div>
<div id="ref-Cole2007">
<p>Cole, J J, Y T Prairie, N F Caraco, W H McDowell, L J Tranvik, R G Striegl, C M Duarte, et al. 2007. “Plumbing the Global Carbon Cycle: Integrating Inland Waters into the Terrestrial Carbon Budget.” <em>Ecosystems</em> 10 (1): 172–85. <a href="https://doi.org/10.1007/s10021-006-9013-8" class="uri">https://doi.org/10.1007/s10021-006-9013-8</a>.</p>
</div>
<div id="ref-Fellman2010">
<p>Fellman, Jason B, Eran Hood, and Robert G M Spencer. 2010. “Fluorescence spectroscopy opens new windows into dissolved organic matter dynamics in freshwater ecosystems: A review.” <em>Limnology and Oceanography</em> 55 (6): 2452–62. <a href="https://doi.org/10.4319/lo.2010.55.6.2452" class="uri">https://doi.org/10.4319/lo.2010.55.6.2452</a>.</p>
</div>
<div id="ref-Foreman2003">
<p>Foreman, C.M., and J.S. Covert. 2003. “Linkages between Dissolved Organic Matter Composition and Bacterial Community Structure.” In <em>Aquatic Ecosystems : Interactivity of Dissolved Organic Matter</em>, 343–62. Elsevier. <a href="https://doi.org/10.1016/B978-012256371-3/50015-9" class="uri">https://doi.org/10.1016/B978-012256371-3/50015-9</a>.</p>
</div>
<div id="ref-Harshman1970">
<p>Harshman, Richard a. 1970. “Foundations of the PARAFAC procedure: Models and conditions for an ‘explanatory’ multimodal factor analysis.” <em>UCLA Working Papers in Phonetics</em> 16 (10): 1–84.</p>
</div>
<div id="ref-Hiriart-Baer2008">
<p>Hiriart-Baer, Véronique P., Ngan Diep, and Ralph E. H. Smith. 2008. “Dissolved Organic Matter in the Great Lakes: Role and Nature of Allochthonous Material.” <em>Journal of Great Lakes Research</em> 34 (3): 383–94. <a href="https://doi.org/10.3394/0380-1330(2008)34%5B383:DOMITG%5D2.0.CO;2" class="uri">https://doi.org/10.3394/0380-1330(2008)34[383:DOMITG]2.0.CO;2</a>.</p>
</div>
<div id="ref-Huguet2009">
<p>Huguet, A., L. Vacher, S. Relexans, S. Saubusse, J.M. Froidefond, and E. Parlanti. 2009. “Properties of fluorescent dissolved organic matter in the Gironde Estuary.” <em>Organic Geochemistry</em> 40 (6). Elsevier Ltd: 706–19. <a href="https://doi.org/10.1016/j.orggeochem.2009.03.002" class="uri">https://doi.org/10.1016/j.orggeochem.2009.03.002</a>.</p>
</div>
<div id="ref-Kirk1994">
<p>Kirk, John T O. 1994. <em>Light and photosynthesis in aquatic ecosystems</em>. 2nd ed. Cambridge [England] ; New York: Cambridge University Press.</p>
</div>
<div id="ref-Kothawala2013">
<p>Kothawala, Dolly N., Kathleen R. Murphy, Colin A. Stedmon, Gesa A. Weyhenmeyer, and Lars J. Tranvik. 2013. “Inner filter correction of dissolved organic matter fluorescence.” <em>Limnology and Oceanography: Methods</em> 11 (12): 616–30. <a href="https://doi.org/10.4319/lom.2013.11.616" class="uri">https://doi.org/10.4319/lom.2013.11.616</a>.</p>
</div>
<div id="ref-Kritzberg2006a">
<p>Kritzberg, Emma S, Jonathan J Cole, Michael M Pace, and Wilhelm Granéli. 2006. “Bacterial Growth on Allochthonous Carbon in Humic and Nutrient-enriched Lakes: Results from Whole-Lake 13C Addition Experiments.” <em>Ecosystems</em> 9 (3): 489–99. <a href="https://doi.org/10.1007/s10021-005-0115-5" class="uri">https://doi.org/10.1007/s10021-005-0115-5</a>.</p>
</div>
<div id="ref-Lakowicz2006">
<p>Lakowicz, Joseph R. 2006. <em>Principles of Fluorescence Spectroscopy</em>. Edited by Joseph R. Lakowicz. Boston, MA: Springer-Verlag. <a href="https://doi.org/10.1007/978-0-387-46312-4" class="uri">https://doi.org/10.1007/978-0-387-46312-4</a>.</p>
</div>
<div id="ref-Lawaetz2009">
<p>Lawaetz, A J, and C A Stedmon. 2009. “Fluorescence Intensity Calibration Using the Raman Scatter Peak of Water.” <em>Applied Spectroscopy</em> 63 (8): 936–40. <a href="https://doi.org/10.1366/000370209788964548" class="uri">https://doi.org/10.1366/000370209788964548</a>.</p>
</div>
<div id="ref-Massicotte2011EA">
<p>Massicotte, Philippe, and Jean-Jacques Frenette. 2011. “Spatial connectivity in a large river system: resolving the sources and fate of dissolved organic matter.” <em>Ecological Applications</em> 21 (7): 2600–2617. <a href="https://doi.org/10.1890/10-1475.1" class="uri">https://doi.org/10.1890/10-1475.1</a>.</p>
</div>
<div id="ref-McKnight2001">
<p>McKnight, Diane M., Elizabeth W. Boyer, Paul K. Westerhoff, Peter T. Doran, Thomas Kulbe, and Dale T. Andersen. 2001. “Spectrofluorometric characterization of dissolved organic matter for indication of precursor organic material and aromaticity.” <em>Limnology and Oceanography</em> 46 (1). American Society of Limnology; Oceanography: 38–48. <a href="https://doi.org/10.4319/lo.2001.46.1.0038" class="uri">https://doi.org/10.4319/lo.2001.46.1.0038</a>.</p>
</div>
<div id="ref-Mobed1996">
<p>Mobed, Jarafshan J, Sherry L Hemmingsen, Jennifer L Autry, and Linda B McGown. 1996. “Fluorescence Characterization of IHSS Humic Substances: Total Luminescence Spectra with Absorbance Correction.” <em>Environmental Science &amp; Technology</em> 30 (10): 3061–5. <a href="https://doi.org/10.1021/es960132l" class="uri">https://doi.org/10.1021/es960132l</a>.</p>
</div>
<div id="ref-Murphy2013">
<p>Murphy, Kathleen R., Colin a. Stedmon, Daniel Graeber, and Rasmus Bro. 2013. “Fluorescence spectroscopy and multi-way techniques. PARAFAC.” <em>Analytical Methods</em> 5 (23): 6557. <a href="https://doi.org/10.1039/c3ay41160e" class="uri">https://doi.org/10.1039/c3ay41160e</a>.</p>
</div>
<div id="ref-Ohno2002">
<p>Ohno, Tsutomu. 2002. “Fluorescence Inner-Filtering Correction for Determining the Humification Index of Dissolved Organic Matter.” <em>Environmental Science &amp; Technology</em> 36 (4): 742–46. <a href="https://doi.org/10.1021/es0155276" class="uri">https://doi.org/10.1021/es0155276</a>.</p>
</div>
<div id="ref-Parker1957">
<p>Parker, C. a., and W. J. Barnes. 1957. “Some experiments with spectrofluorimeters and filter fluorimeters.” <em>The Analyst</em> 82 (978): 606. <a href="https://doi.org/10.1039/an9578200606" class="uri">https://doi.org/10.1039/an9578200606</a>.</p>
</div>
<div id="ref-Seitzinger2005">
<p>Seitzinger, S P, H Hartnett, R Lauck, M Mazurek, T Minegishi, G Spyres, and R Styles. 2005. “Molecular-level chemical characterization and bioavailability of dissolved organic matter in stream water using electrospray-ionization mass spectrometry.” <em>Limnology and Oceanography</em> 50 (1). Seitzinger, SP Rutgers State Univ, Inst Marine &amp; Coastal Sci, 71 Dudley Rd, New Brunswick, NJ 08901 USA Rutgers State Univ, Inst Marine &amp; Coastal Sci, New Brunswick, NJ 08901 USA: 1–12. <a href="https://doi.org/10.4319/lo.2005.50.1.0001" class="uri">https://doi.org/10.4319/lo.2005.50.1.0001</a>.</p>
</div>
<div id="ref-Stedmon2008">
<p>Stedmon, Colin A, and Rasmus Bro. 2008. “Characterizing dissolved organic matter fluorescence with parallel factor analysis: a tutorial.” <em>Limnology and Oceanography: Methods</em> 6 (11): 572–79. <a href="https://doi.org/10.4319/lom.2008.6.572" class="uri">https://doi.org/10.4319/lom.2008.6.572</a>.</p>
</div>
<div id="ref-Stedmon2003a">
<p>Stedmon, Colin A, Stiig Markager, and Rasmus Bro. 2003. “Tracing dissolved organic matter in aquatic environments using a new approach to fluorescence spectroscopy.” <em>Marine Chemistry</em> 82 (3-4): 239–54. <a href="https://doi.org/10.1016/S0304-4203(03)00072-0" class="uri">https://doi.org/10.1016/S0304-4203(03)00072-0</a>.</p>
</div>
<div id="ref-Zepp2004">
<p>Zepp, Richard G, Wade M Sheldon, and Mary Ann Moran. 2004. “Dissolved organic fluorophores in southeastern US coastal waters: correction method for eliminating Rayleigh and Raman scattering peaks in excitation–emission matrices.” <em>Marine Chemistry</em> 89 (1-4): 15–36. <a href="https://doi.org/10.1016/j.marchem.2004.02.006" class="uri">https://doi.org/10.1016/j.marchem.2004.02.006</a>.</p>
</div>
</div>
</div>
  </div>

  <div class="col-md-3 hidden-xs hidden-sm" id="sidebar">
        <div id="tocnav">
      <h2 class="hasAnchor">
<a href="#tocnav" class="anchor"></a>Contents</h2>
      <ul class="nav nav-pills nav-stacked">
<li><a href="#introduction">Introduction</a></li>
      <li><a href="#fluorescence-of-dom-theoretical-and-mathematical-background">Fluorescence of DOM: theoretical and mathematical background</a></li>
      <li><a href="#r-code-and-study-case">R code and study case</a></li>
      <li><a href="#using-r-pipeline">Using R pipeline</a></li>
      <li><a href="#conclusion">Conclusion</a></li>
      <li><a href="#references">References</a></li>
      </ul>
</div>
      </div>

</div>


      <footer><div class="copyright">
  <p>Developed by Philippe Massicotte.</p>
</div>

<div class="pkgdown">
  <p>Site built with <a href="https://pkgdown.r-lib.org/">pkgdown</a> 1.3.0.</p>
</div>
      </footer>
</div>

  

  </body>
</html>
