# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Faster read lines
#'
#' @param path File name or folder containing fluorescence file(s).
read_lines <- function(path) {
    .Call('eemR_read_lines', PACKAGE = 'eemR', path)
}

